// DO NOT EDIT THIS FILE
#pragma once

#include <stack>
#include <queue>
#include <string>


int countLegoHouses(std::string recipe, std::string bucket);

std::vector<std::string> findLargestAnagroup(const std::vector<std::string>& words);

std::vector<double> mergeSortedLists(const std::vector<std::vector<double>>& sortedVecs);